### ISSUE TITLE
Place for Announcements?

### ISSUE THREAD

**Issue by clarkmalmgren** [clarkmalmgren/bolingbrook-church#31]

**Comment by clarkmalmgren** [comment]
@jstphard, This isn't super common, but sometimes, I get requests to add small amounts of detail to the website like registration links, upcoming events, surveys, etc.

I am thinking that it might make sense to add a section for announcements to cover these kinds of common updates. The design is still TBD in my head, but I am thinking that the basic premise is that a list of all announcements would be made available at `https://bolingbrook.church/announcements`. We could also create direct links to specific announcements using links like `https://bolingbrook.church/announcements/vbs2017`. To shorten the link, we could also provide a redirect from something like `https://bolingbrook.church/a/vbs2017`.

What do you think?

**Comment by Nalielle** [comment]
Hey @clarkmalmgren & @jstphard I like the idea of maybe even changing announcements to Upcoming Events since that's what we call it on Saturdays. And then maybe something that looks sort of like this 
![events](https://user-images.githubusercontent.com/30123695/28128546-ad5a6340-66f5-11e7-937c-5fc0372c600f.jpg)  right on the menu page (don't know if that makes sense to have their) but then from there people are 2 clicks away from all info like this --->

![screen shot 2017-07-12 at 11 25 57 am](https://user-images.githubusercontent.com/30123695/28128574-c72f6a68-66f5-11e7-951a-6e2aec894f32.png)

I think I prefer something like this vs a google calendar. Or something like this since we usually have slides for each upcoming Events

![screen shot 2017-07-12 at 11 33 31 am](https://user-images.githubusercontent.com/30123695/28128657-0e9036e4-66f6-11e7-8c34-3f77eea82b40.png)

From there we can have the info page for that event more like 3 clicks but still makes more sense.

**Comment by jstphard** [comment]
LOVE THIS!



*Jose St. Phard *Bolingbrook Church
Lead Pastor
301 E. Boughton Rd.
Bolingbrook IL, 60440, USA

Office 630-739-1038
Jose.saintphard@bolingbrook.church
www.bolingbrook.church

*This email and any attachments may be privileged and may
contain confidential information intended only for the recipient(s) named
above. Any other distribution, forwarding, copying or disclosure of this
message is strictly prohibited.*
